#' Localised namespace names.
#'
#' A dataset generated by \code{\link{namespace_match_generator}}, \code{namespace_names}
#' is used by \code{\link{namespace_match}} to convert namespace IDs to localised names, and
#' vice versa.
#'
#' @format A data.table with 5 variables:
#' \describe{
#'   \item{language}{The english-language name for the language of the project this localised name is from.}
#'   \item{project_type}{The project type ('wiki', 'wikisource', and so on)}
#'   \item{db}{The database name, following the same format used by the NOC lists and analytics-store.eqiad.wmnet}
#'   \item{namespace}{The namespace ID}
#'   \item{name}{The localised namespace name}
#' }
#' @name namespace_names
NULL