# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_intertimes <- function(timestamps) {
    .Call('WMUtils_cpp_intertimes', PACKAGE = 'WMUtils', timestamps)
}

#' @title
#' session_count
#' @description
#' Session counting function
#' 
#' @param x a vector of intertime values
#' 
#' @param local_minimum the threshold (in seconds) to split out a new session on. Set to 3600
#' by default.
#' 
#' @details
#' \code{session_count} takes a vector of intertime values (generated via \code{\link{intertimes}},
#' or in any other way you see fit) and returns the total number of sessions within that dataset.
#' It's implimented in C++, providing a (small) increase in speed over the R equivalent.
#' 
#' @seealso
#' \code{\link{intertimes}}, for generating inter-time values.
#' @export
session_count <- function(x, local_minimum = 3600L) {
    .Call('WMUtils_session_count', PACKAGE = 'WMUtils', x, local_minimum)
}

